/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Nat;
export const LuckyNumberSetId = IDL.Nat;
export const Game = IDL.Record({
  'id' : GameId,
  'colorTheme' : IDL.Text,
  'name' : IDL.Text,
  'drawTime' : IDL.Int,
});
export const LuckyNumberSet = IDL.Record({
  'id' : LuckyNumberSetId,
  'gameId' : GameId,
  'timestamp' : IDL.Int,
  'numbers' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'createGame' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [GameId], []),
  'deleteGame' : IDL.Func([GameId], [], []),
  'generateAndSaveLuckyNumbers' : IDL.Func([GameId], [LuckyNumberSetId], []),
  'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getAllLuckyNumberSets' : IDL.Func([], [IDL.Vec(LuckyNumberSet)], ['query']),
  'getGame' : IDL.Func([GameId], [Game], ['query']),
  'getLuckyNumberSet' : IDL.Func(
      [LuckyNumberSetId],
      [LuckyNumberSet],
      ['query'],
    ),
  'getLuckyNumberSetsForGame' : IDL.Func(
      [GameId],
      [IDL.Vec(LuckyNumberSet)],
      ['query'],
    ),
  'updateGame' : IDL.Func([GameId, IDL.Text, IDL.Int, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Nat;
  const LuckyNumberSetId = IDL.Nat;
  const Game = IDL.Record({
    'id' : GameId,
    'colorTheme' : IDL.Text,
    'name' : IDL.Text,
    'drawTime' : IDL.Int,
  });
  const LuckyNumberSet = IDL.Record({
    'id' : LuckyNumberSetId,
    'gameId' : GameId,
    'timestamp' : IDL.Int,
    'numbers' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'createGame' : IDL.Func([IDL.Text, IDL.Int, IDL.Text], [GameId], []),
    'deleteGame' : IDL.Func([GameId], [], []),
    'generateAndSaveLuckyNumbers' : IDL.Func([GameId], [LuckyNumberSetId], []),
    'getAllGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getAllLuckyNumberSets' : IDL.Func(
        [],
        [IDL.Vec(LuckyNumberSet)],
        ['query'],
      ),
    'getGame' : IDL.Func([GameId], [Game], ['query']),
    'getLuckyNumberSet' : IDL.Func(
        [LuckyNumberSetId],
        [LuckyNumberSet],
        ['query'],
      ),
    'getLuckyNumberSetsForGame' : IDL.Func(
        [GameId],
        [IDL.Vec(LuckyNumberSet)],
        ['query'],
      ),
    'updateGame' : IDL.Func([GameId, IDL.Text, IDL.Int, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };