/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Game {
    id: GameId;
    colorTheme: string;
    name: string;
    drawTime: bigint;
}
export type LuckyNumberSetId = bigint;
export interface LuckyNumberSet {
    id: LuckyNumberSetId;
    gameId: GameId;
    timestamp: bigint;
    numbers: Array<bigint>;
}
export type GameId = bigint;
export interface backendInterface {
    createGame(name: string, drawTime: bigint, colorTheme: string): Promise<GameId>;
    deleteGame(gameId: GameId): Promise<void>;
    generateAndSaveLuckyNumbers(gameId: GameId): Promise<LuckyNumberSetId>;
    getAllGames(): Promise<Array<Game>>;
    getAllLuckyNumberSets(): Promise<Array<LuckyNumberSet>>;
    getGame(gameId: GameId): Promise<Game>;
    getLuckyNumberSet(luckyNumberSetId: LuckyNumberSetId): Promise<LuckyNumberSet>;
    getLuckyNumberSetsForGame(gameId: GameId): Promise<Array<LuckyNumberSet>>;
    updateGame(gameId: GameId, name: string, drawTime: bigint, colorTheme: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createGame(arg0: string, arg1: bigint, arg2: string): Promise<GameId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGame(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGame(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteGame(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGame(arg0);
            return result;
        }
    }
    async generateAndSaveLuckyNumbers(arg0: GameId): Promise<LuckyNumberSetId> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAndSaveLuckyNumbers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAndSaveLuckyNumbers(arg0);
            return result;
        }
    }
    async getAllGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGames();
            return result;
        }
    }
    async getAllLuckyNumberSets(): Promise<Array<LuckyNumberSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLuckyNumberSets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLuckyNumberSets();
            return result;
        }
    }
    async getGame(arg0: GameId): Promise<Game> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return result;
        }
    }
    async getLuckyNumberSet(arg0: LuckyNumberSetId): Promise<LuckyNumberSet> {
        if (this.processError) {
            try {
                const result = await this.actor.getLuckyNumberSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLuckyNumberSet(arg0);
            return result;
        }
    }
    async getLuckyNumberSetsForGame(arg0: GameId): Promise<Array<LuckyNumberSet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLuckyNumberSetsForGame(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLuckyNumberSetsForGame(arg0);
            return result;
        }
    }
    async updateGame(arg0: GameId, arg1: string, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGame(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGame(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
